name: Simple GitHub Actions Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a simple test
        run: echo "Hello, GitHub Actions!"
